### ISSUE TITLE
Use the nested set model for storage

### ISSUE THREAD

**Issue by cmc333333** [eregs/regulations-core#2]
Currently, when storing the regulation tree, we store _each_ subtree, keyed by label. While this makes processing very simple, it leads to a great deal of redundancy and can be quite slow when importing the tree (as the structure must be walked and each subtree inserted).

An alternative is the [nested set model](http://en.wikipedia.org/wiki/Nested_set_model), which stores each node once but makes grabbing subtrees (equivalent to subsets) painless. There's even a [few](https://github.com/django-mptt/django-mptt) [implementations](https://pypi.python.org/pypi/django-treebeard) in django.

**Comment by jmcarp** [comment]
@cmc333333: is the idea that we'd be able to drop `Regulation#children` and still get all descendants of a given regulation node in a single query using django-mptt or django-treebeard? I'd be down to give this a try once I'm confident I understand what we want to accomplish.

**Comment by cmc333333** [comment]
That sounds right to me -- the goal is to reduce the redundant storage (thereby speeding up POST/PUTs) while maintaining the same external-facing API (at roughly the same speed). Does that help?
