### ISSUE TITLE
Search always returns "no results"

### ISSUE THREAD

**Issue by eadamsatx** [eregs/regulations-core#60]
Whether using elasticsearch (was able to get a successful import on 12 CFR 1008) or haystack/solr for storage, search always seems to return "not found."  Am I missing something obvious?

**Comment by cmc333333** [comment]
Hi again @eadamsatx. One potential solution:
```bash
python manage.py rebuild_index
```
We don't have haystack configured to incrementally build the index (as we dump a bunch of documents in at once).

Regarding Elastic, what version are you currently running? It's possible that all the query code was written for an outdated version of Elastic, in which case we should just chuck it and make our lives easier with haystack.

**Comment by cmc333333** [comment]
Hey @eadamsatx did `rebuild_index` work?

**Comment by eadamsatx** [comment]
Well, not initially, but after I did the build_solr_schema, dropped the schema.xml in the right place and ran rebuild_index, I did get it to work.  Thanks.
