### ISSUE TITLE
Update mention of example_settings.py in README.md

### ISSUE THREAD

**Issue by gregoryfoster** [eregs/regulations-core#61]
Hi, I'm new to `regulations-core` and a relative Python newb, so my apologies in advance should I miss the obvious.  Helpful pointers welcome!

In walking through the documentation on [building `regulations-core` from source](https://github.com/eregs/regulations-core#from-source), there's mention of an `example_settings.py` file which I'm unable to find in the source repository.  Should this be a reference to `regcore/settings/base.py`?

Thank you!

**Comment by cmc333333** [comment]
Good call, @gregoryfoster, it should be regcore/settings/base.py (as configured [here](https://github.com/eregs/regulations-core/blob/master/manage.py#L6)). Would you mind making a PR?

The relationship between -parser, -core, and -site can be pretty confusing. You might want to poke at a specific use case, like [ATF's repo](https://github.com/18F/atf-eregs/). In particular, their [Docker setup](https://atf-eregs.readthedocs.io/en/latest/docker_setup.html) should get you going pretty fast.

**Comment by cmc333333** [comment]
Also, thanks for taking a look! Feel free to reach out through issues; we can work through any issues you run into.

**Comment by cmc333333** [comment]
Resolved by #62
